### PR TITLE
Update entryController.js

### PR DESCRIPTION
**Pull request by tnrich**
adding onPaste functionality, adjusting to allow for new panels layout

### CODE REVIEW

**Comment by tnrich** [comment]
@hplahar any reason you're not merging this?

**Comment by hplahar** [comment]
I have not had the chance to test it yet; it will likely make its way into ICE releases (and production) before I am ready for it to, requiring manual changes. If you need it on the test server I recommend manually editing the deployed files on registry-test2. I believe you have access to the server?

**Comment by tnrich** [comment]
Ah okay interesting, are those manual changes persisted on the test server? I don't have any particular urgency but Nathan can't QA until those changes make it.

**Comment by hplahar** [comment]
Yes, if the changes are made to the deployed version in /var/lib/tomcat6/webapps/ROOT. (at least until I deploy a new version but I don't update registry-test2 frequently)

**Pull request closed without merging**
